In [177]:
import pandas
import numpy as np
import math
raw_data = pandas.read_csv('all_enrolments.csv')
raw_data.head()

,code_module,code_presentation,id_student,date_registration,date_unregistration,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,total_activity,days_active,last_active_date,distinct_content_items_accessed,final_assessment_score,final_exam_score
0,AAA,2013J,11391,-159.0,NaN,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass,934.0,40.0,253.0,55.0,82.4,NaN
1,AAA,2013J,28400,-53.0,NaN,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass,1435.0,80.0,239.0,84.0,65.4,NaN
2,AAA,2013J,30268,-92.0,12.0,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn,281.0,12.0,12.0,22.0,NaN,NaN
3,AAA,2013J,31604,-52.0,NaN,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass,2158.0,123.0,264.0,82.0,76.3,NaN
4,AAA,2013J,32885,-176.0,NaN,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass,1034.0,70.0,247.0,66.0,55.0,NaN

In [200]:
code_module_enums = set()
highest_education_enums = set()
region_enums = set()
code_presentation_enums = set()
gender_enums = set()
disability_enums = set()
for highest_education in raw_data['highest_education']:
    highest_education_enums.add(highest_education)
for region in raw_data['region']:
    region_enums.add(region)
for code_presentation in raw_data['code_presentation']:
    code_presentation_enums.add(code_presentation)
for gender in raw_data['gender']:
    gender_enums.add(gender)
for disability in raw_data["disability"]:
    disability_enums.add(disability)
for code_module in raw_data['code_module']:
    code_module_enums.add(code_module)
    
print(code_module_enums)
print(highest_education_enums)
print(region_enums)
print(code_presentation_enums)
print(raw_data.shape)
print(gender_enums)
print(disability_enums)

num_useful_features = 5 + len(highest_education_enums) + len(region_enums) + len(gender_enums) + len(disability_enums) + len(code_module_enums)



print(num_useful_features)

imd_band_map = {
    '90-100' : 0.95,
    '80-90' : 0.85,
    '70-80' : 0.75,
    '60-70' : 0.65,
    '50-60' : 0.55,
    '40-50' : 0.45,
    '30-40' : 0.35,
    '20-30' : 0.25,
    '10-20' : 0.15,
    '0-10' : 0.05,
}
age_band_map = {
    '0-35': 0.38,
    '35-55': 0.72,
    '55<=': 1
}

cleaned_data = np.zeros((0, num_useful_features))
assessment_scores = np.array([])


for index, row in raw_data.iterrows():
    if not math.isnan(row['final_assessment_score']):
        assessment_scores = np.append(assessment_scores, [row['final_assessment_score']])
        cleaned_row = np.zeros(num_useful_features)
        code_module = row['code_module']
        gender = row['gender']
        region = row['region']
        highest_education = row['highest_education']
        disability = row['disability']
        date_registration = row['date_registration']
        imd_band_raw = row['imd_band']
        imd_band = 0
        num_of_prev_attempts = row['num_of_prev_attempts']
        studied_credits = row['studied_credits']
        if (pandas.isnull(num_of_prev_attempts)):
            num_of_prev_attempts = 0
        if (pandas.isnull(date_registration)):
            date_registration = 0
        if (pandas.isnull(studied_credits)):
            studied_credits = 0
        
        if (pandas.isnull(imd_band_raw)):
            cleaned_row[28] = 0.5
        else:
            if (imd_band_raw[len(imd_band_raw) - 1] == '%'):
                imd_band_raw = imd_band_raw[:-1]
            cleaned_row[28] = imd_band_map[imd_band_raw]
        age_band = row['age_band']
        if (code_module == 'AAA'):
            cleaned_row[0] = 1
        if (code_module == 'BBB'):
            cleaned_row[1] = 1
        if (code_module == 'CCC'):
            cleaned_row[2] = 1
        if (code_module == 'DDD'):
            cleaned_row[3] = 1
        if (code_module == 'EEE'):
            cleaned_row[4] = 1
        if (code_module == 'FFF'):
            cleaned_row[5] = 1
        if (code_module == 'GGG'):
            cleaned_row[6] = 1
        cleaned_row[7] = date_registration
        if (gender == 'M'):
            cleaned_row[8] = 1
        if (gender == 'F'):
            cleaned_row[9] = 1
        if (region == 'South Region'):
            cleaned_row[10] = 1
        if (region == 'London Region'):
            cleaned_row[11] = 1
        if (region == 'West Midlands Region'):
            cleaned_row[12] = 1
        if (region == 'North Western Region'):
            cleaned_row[13] = 1
        if (region == 'Ireland'):
            cleaned_row[14] = 1
        if (region == 'South East Region'):
            cleaned_row[15] = 1
        if (region == 'Scotland'):
            cleaned_row[16] = 1
        if (region == 'Yorkshire Region'):
            cleaned_row[17] = 1
        if (region == 'Wales'):
            cleaned_row[18] = 1
        if (region == 'East Midlands Region'):
            cleaned_row[19] = 1
        if (region == 'South West Region'):
            cleaned_row[20] = 1
        if (region == 'North Region'):
            cleaned_row[21] = 1
        if (region == 'East Anglian Region'):
            cleaned_row[22] = 1
        if (highest_education == 'HE Qualification'):
            cleaned_row[23] = 1
        if (highest_education == 'Post Graduate Qualification'):
            cleaned_row[24] = 1
        if (highest_education == 'No Formal quals'):
            cleaned_row[25] = 1
        if (highest_education == 'Lower Than A Level'):
            cleaned_row[26] = 1
        if (highest_education == 'A Level or Equivalent'):
            cleaned_row[27] = 1
        
        
        cleaned_row[29] = age_band_map[row['age_band']]
        cleaned_row[30] = num_of_prev_attempts
        cleaned_row[31] = studied_credits
        if (disability == 'Y'):
            cleaned_row[32] = 1
        if (disability == 'N'):
            cleaned_row[33] = 1

        cleaned_data = np.vstack([cleaned_data, cleaned_row])


print(cleaned_data[0])

{'CCC', 'DDD', 'BBB', 'EEE', 'GGG', 'FFF', 'AAA'}
{'HE Qualification', 'Post Graduate Qualification', 'No Formal quals', 'Lower Than A Level', 'A Level or Equivalent'}
{'South Region', 'London Region', 'West Midlands Region', 'North Western Region', 'Ireland', 'South East Region', 'Scotland', 'Yorkshire Region', 'Wales', 'East Midlands Region', 'South West Region', 'North Region', 'East Anglian Region'}
{'2014B', '2014J', '2013B', '2013J'}
(32593, 20)
{'M', 'F'}
{'N', 'Y'}
34
[   1.      0.      0.      0.      0.      0.      0.   -159.      1.
    0.      0.      0.      0.      0.      0.      0.      0.      0.
    0.      0.      0.      0.      1.      1.      0.      0.      0.
    0.      0.95    1.      0.    240.      0.      1.  ]

In [74]:
#raw_data = raw_data[raw_data['code_module'] == 'BBB']
##raw_data = raw_data[raw_data['code_presentation'] == '2014J']
#highest_education_enums = set()
#for highest_education in raw_data['highest_education']
#    set.add(highest_education)

#data = pandas.DataFrame()
#data['label'] = raw_data['final_result'].apply(lambda x: 1 if x == 'Pass' or x == 'Distinction' else 0)

#features = ['gender', 'highest_education', 'imd_band', 'age_band', 'disability']
#for feature in features:
#    data = pandas.concat([data, pandas.get_dummies(raw_data[feature], prefix=feature)], axis=1)
#data.info()

SyntaxError: invalid syntax (<ipython-input-74-c6341cca590f>, line 4)

In [220]:
from sklearn.metrics import mean_squared_error, r2_score
#X = data.drop('label', axis=1)
#y = data['label']

stds = np.std(cleaned_data, axis=0)
means = np.mean(cleaned_data, axis=0)


print(cleaned_data[0])


for i in range(len(cleaned_data)):
    cleaned_data[i][7] = np.true_divide((cleaned_data[i][7] - means[7]), stds[7])
    cleaned_data[i][31] = np.true_divide((cleaned_data[i][31] - means[31]), stds[31])
    
print(cleaned_data[0])
print(np.mean(cleaned_data, axis = 0))


X_train, X_test, y_train, y_test = train_test_split(cleaned_data, assessment_scores, test_size=0.3)

[ 1.          0.          0.          0.          0.          0.          0.
 -1.94798468  1.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          1.          1.          0.          0.          0.          0.
  0.95        1.          0.          4.26341895  0.          1.        ]
[ 1.          0.          0.          0.          0.          0.          0.
 -1.94798468  1.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          1.          1.          0.          0.          0.          0.
  0.95        1.          0.          4.26341895  0.          1.        ]
[  2.72699101e-02   2.35202975e-01   1.32166099e-01   1.91199256e-01
   8.89758289e-02   2.43492408e-01   8.16935234e-02  -9.75057586e-17
   5.50046483e-01   4.49953517e-01   9.74202045e-02   9.37015804e-02
   7.60381159e-02   8.41726061e-02   4.04400372e-02   6.53470716e-02
   1.09931825e-01   6.02339634e-02   6.71289123e-02   7.12348931e-02
   7.59606446e-02   5.57793616e-02   1.02610784e-01   1.54516579e-01
   1.08072513e-02   8.83173226e-03   3.80965293e-01   4.44879145e-01
   4.84761388e-01   4.85850635e-01   1.56569569e-01  -1.87284853e-14
   9.35853734e-02   9.06414627e-01]

In [216]:
clf = svm.SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.2, gamma='auto',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)
clf.fit(X_test, y_test)

print(clf.score(X_train, y_train))

0.269819280495

In [5]:
import pickle


with open('model.pkl', 'wb') as f:
    pickle.dump(clf, f, 4)

dummy_map = dict(zip(X.columns, range(X.shape[1])))
with open('map.pkl', 'wb') as f:
    pickle.dump(dummy_map, f, 4)
print(dummy_map)

{'gender_F': 0, 'gender_M': 1, 'highest_education_A Level or Equivalent': 2, 'highest_education_HE Qualification': 3, 'highest_education_Lower Than A Level': 4, 'highest_education_No Formal quals': 5, 'highest_education_Post Graduate Qualification': 6, 'imd_band_0-10%': 7, 'imd_band_10-20': 8, 'imd_band_20-30%': 9, 'imd_band_30-40%': 10, 'imd_band_40-50%': 11, 'imd_band_50-60%': 12, 'imd_band_60-70%': 13, 'imd_band_70-80%': 14, 'imd_band_80-90%': 15, 'imd_band_90-100%': 16, 'age_band_0-35': 17, 'age_band_35-55': 18, 'age_band_55<=': 19, 'disability_N': 20, 'disability_Y': 21}

In [6]:
with open('model.pkl', 'rb') as f:
    clf = pickle.load(f)
with open('map.pkl', 'rb') as f:
    dummy_map = pickle.load(f)

X = [0] * len(dummy_map)
X[dummy_map['gender_M']] = 1
X[dummy_map['highest_education_A Level or Equivalent']] = 1
X[dummy_map['imd_band_0-10%']] = 1
X[dummy_map['age_band_0-35']] = 1
X[dummy_map['disability_N']] = 1
print(clf.predict([X]))

X[dummy_map['highest_education_A Level or Equivalent']] = 0
X[dummy_map['highest_education_Lower Than A Level']] = 1
print(clf.predict([X]))

X[dummy_map['imd_band_0-10%']] = 0
X[dummy_map['imd_band_90-100%']] = 1
print(clf.predict([X]))

X[dummy_map['disability_N']] = 0
X[dummy_map['disability_Y']] = 1
print(clf.predict([X]))

[1]
[1]
[1]
[1]